<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DeliveryPrice;

class DeliveryPriceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * ข้อมูลทั้งหมด 160 แขวงจาก CSV ที่ถูกต้องเท่านั้น
     */
    public function run(): void
    {
        $deliveryPrices = [
            ['district_name' => 'แขวงคลองเตย', 'grab_motorcycle_price' => 133, 'grab_car_price' => 240, 'lalamove_motorcycle_price' => 109, 'lalamove_car_price' => 173],
            ['district_name' => 'แขวงคลองตัน', 'grab_motorcycle_price' => 108, 'grab_car_price' => 195, 'lalamove_motorcycle_price' => 103, 'lalamove_car_price' => 191],
            ['district_name' => 'แขวงพระโขนง', 'grab_motorcycle_price' => 111, 'grab_car_price' => 190, 'lalamove_motorcycle_price' => 93, 'lalamove_car_price' => 191],
            ['district_name' => 'แขวงคลองต้นไทร', 'grab_motorcycle_price' => 179, 'grab_car_price' => 324, 'lalamove_motorcycle_price' => 177, 'lalamove_car_price' => 235],
            ['district_name' => 'แขวงคลองสาน', 'grab_motorcycle_price' => 187, 'grab_car_price' => 339, 'lalamove_motorcycle_price' => 167, 'lalamove_car_price' => 274],
            ['district_name' => 'แขวงบางลำภูล่าง', 'grab_motorcycle_price' => 193, 'grab_car_price' => 336, 'lalamove_motorcycle_price' => 173, 'lalamove_car_price' => 264],
            ['district_name' => 'แขวงสมเด็จเจ้าพระยา', 'grab_motorcycle_price' => 181, 'grab_car_price' => 300, 'lalamove_motorcycle_price' => 161, 'lalamove_car_price' => 216],
            ['district_name' => 'แขวงทรายกองดิน', 'grab_motorcycle_price' => 232, 'grab_car_price' => 333, 'lalamove_motorcycle_price' => 183, 'lalamove_car_price' => 252],
            ['district_name' => 'แขวงทรายกองดินใต้', 'grab_motorcycle_price' => 196, 'grab_car_price' => 348, 'lalamove_motorcycle_price' => 184, 'lalamove_car_price' => 253],
            ['district_name' => 'แขวงบางชัน', 'grab_motorcycle_price' => 171, 'grab_car_price' => 317, 'lalamove_motorcycle_price' => 146, 'lalamove_car_price' => 212],
            ['district_name' => 'แขวงสามวาตะวันตก', 'grab_motorcycle_price' => 496, 'grab_car_price' => 697, 'lalamove_motorcycle_price' => 180, 'lalamove_car_price' => 250],
            ['district_name' => 'แขวงสามวาตะวันออก', 'grab_motorcycle_price' => 210, 'grab_car_price' => 416, 'lalamove_motorcycle_price' => 204, 'lalamove_car_price' => 276],
            ['district_name' => 'แขวงคันนายาว', 'grab_motorcycle_price' => 130, 'grab_car_price' => 304, 'lalamove_motorcycle_price' => 143, 'lalamove_car_price' => 189],
            ['district_name' => 'แขวงจตุจักร', 'grab_motorcycle_price' => 167, 'grab_car_price' => 332, 'lalamove_motorcycle_price' => 123, 'lalamove_car_price' => 184],
            ['district_name' => 'แขวงจอมพล', 'grab_motorcycle_price' => 153, 'grab_car_price' => 341, 'lalamove_motorcycle_price' => 110, 'lalamove_car_price' => 170],
            ['district_name' => 'แขวงจันทรเกษม', 'grab_motorcycle_price' => 141, 'grab_car_price' => 358, 'lalamove_motorcycle_price' => 109, 'lalamove_car_price' => 212],
            ['district_name' => 'แขวงลาดยาว', 'grab_motorcycle_price' => 158, 'grab_car_price' => 358, 'lalamove_motorcycle_price' => 142, 'lalamove_car_price' => 201],
            ['district_name' => 'แขวงเสนานิคม', 'grab_motorcycle_price' => 166, 'grab_car_price' => 361, 'lalamove_motorcycle_price' => 188, 'lalamove_car_price' => 279],
            ['district_name' => 'แขวงจอมทอง', 'grab_motorcycle_price' => 225, 'grab_car_price' => 469, 'lalamove_motorcycle_price' => 219, 'lalamove_car_price' => 278],
            ['district_name' => 'แขวงบางขุนเทียน', 'grab_motorcycle_price' => 292, 'grab_car_price' => 523, 'lalamove_motorcycle_price' => 220, 'lalamove_car_price' => 359],
            ['district_name' => 'แขวงบางค้อ', 'grab_motorcycle_price' => 225, 'grab_car_price' => 476, 'lalamove_motorcycle_price' => 210, 'lalamove_car_price' => 332],
            ['district_name' => 'แขวงบางมด', 'grab_motorcycle_price' => 250, 'grab_car_price' => 427, 'lalamove_motorcycle_price' => 209, 'lalamove_car_price' => 283],
            ['district_name' => 'แขวงสีกัน', 'grab_motorcycle_price' => 297, 'grab_car_price' => 538, 'lalamove_motorcycle_price' => 289, 'lalamove_car_price' => 337],
            ['district_name' => 'แขวงดินแดง', 'grab_motorcycle_price' => 112, 'grab_car_price' => 228, 'lalamove_motorcycle_price' => 106, 'lalamove_car_price' => 196],
            ['district_name' => 'แขวงดุสิต', 'grab_motorcycle_price' => 157, 'grab_car_price' => 282, 'lalamove_motorcycle_price' => 173, 'lalamove_car_price' => 206],
            ['district_name' => 'แขวงถนนนครไชยศรี', 'grab_motorcycle_price' => 160, 'grab_car_price' => 285, 'lalamove_motorcycle_price' => 163, 'lalamove_car_price' => 204],
            ['district_name' => 'แขวงวชิรพยาบาล', 'grab_motorcycle_price' => 166, 'grab_car_price' => 264, 'lalamove_motorcycle_price' => 164, 'lalamove_car_price' => 211],
            ['district_name' => 'แขวงสวนจิตรลดา', 'grab_motorcycle_price' => 142, 'grab_car_price' => 245, 'lalamove_motorcycle_price' => 164, 'lalamove_car_price' => 199],
            ['district_name' => 'แขวงสี่แยกมหานาค', 'grab_motorcycle_price' => 152, 'grab_car_price' => 236, 'lalamove_motorcycle_price' => 184, 'lalamove_car_price' => 199],
            ['district_name' => 'แขวงคลองชักพระ', 'grab_motorcycle_price' => 203, 'grab_car_price' => 336, 'lalamove_motorcycle_price' => 194, 'lalamove_car_price' => 281],
            ['district_name' => 'แขวงฉิมพลี', 'grab_motorcycle_price' => 230, 'grab_car_price' => 375, 'lalamove_motorcycle_price' => 195, 'lalamove_car_price' => 267],
            ['district_name' => 'แขวงตลิ่งชัน', 'grab_motorcycle_price' => 283, 'grab_car_price' => 499, 'lalamove_motorcycle_price' => 201, 'lalamove_car_price' => 338],
            ['district_name' => 'แขวงบางเชือกหนัง', 'grab_motorcycle_price' => 265, 'grab_car_price' => 462, 'lalamove_motorcycle_price' => 224, 'lalamove_car_price' => 294],
            ['district_name' => 'แขวงบางพรม', 'grab_motorcycle_price' => 241, 'grab_car_price' => 407, 'lalamove_motorcycle_price' => 193, 'lalamove_car_price' => 264],
            ['district_name' => 'แขวงบางระมาด', 'grab_motorcycle_price' => 244, 'grab_car_price' => 412, 'lalamove_motorcycle_price' => 218, 'lalamove_car_price' => 308],
            ['district_name' => 'แขวงทวีวัฒนา', 'grab_motorcycle_price' => 365, 'grab_car_price' => 578, 'lalamove_motorcycle_price' => 297, 'lalamove_car_price' => 339],
            ['district_name' => 'แขวงศาลาธรรมสพน์', 'grab_motorcycle_price' => 319, 'grab_car_price' => 489, 'lalamove_motorcycle_price' => 262, 'lalamove_car_price' => 317],
            ['district_name' => 'แขวงทุ่งครุ', 'grab_motorcycle_price' => 319, 'grab_car_price' => 438, 'lalamove_motorcycle_price' => 206, 'lalamove_car_price' => 297],
            ['district_name' => 'แขวงดาวคะนอง', 'grab_motorcycle_price' => 209, 'grab_car_price' => 381, 'lalamove_motorcycle_price' => 193, 'lalamove_car_price' => 312],
            ['district_name' => 'แขวงตลาดพลู', 'grab_motorcycle_price' => 207, 'grab_car_price' => 378, 'lalamove_motorcycle_price' => 207, 'lalamove_car_price' => 294],
            ['district_name' => 'แขวงบางยี่เรือ', 'grab_motorcycle_price' => 191, 'grab_car_price' => 365, 'lalamove_motorcycle_price' => 188, 'lalamove_car_price' => 285],
            ['district_name' => 'แขวงบุคคโล', 'grab_motorcycle_price' => 203, 'grab_car_price' => 372, 'lalamove_motorcycle_price' => 231, 'lalamove_car_price' => 281],
            ['district_name' => 'แขวงวัดกัลยาณ์', 'grab_motorcycle_price' => 191, 'grab_car_price' => 328, 'lalamove_motorcycle_price' => 170, 'lalamove_car_price' => 247],
            ['district_name' => 'แขวงสำเหร่', 'grab_motorcycle_price' => 204, 'grab_car_price' => 351, 'lalamove_motorcycle_price' => 188, 'lalamove_car_price' => 280],
            ['district_name' => 'แขวงหิรัญรูจี', 'grab_motorcycle_price' => 192, 'grab_car_price' => 343, 'lalamove_motorcycle_price' => 202, 'lalamove_car_price' => 281],
            ['district_name' => 'แขวงท่าแร้ง', 'grab_motorcycle_price' => 157, 'grab_car_price' => 280, 'lalamove_motorcycle_price' => 153, 'lalamove_car_price' => 213],
            ['district_name' => 'แขวงอนุสาวรีย์', 'grab_motorcycle_price' => 208, 'grab_car_price' => 359, 'lalamove_motorcycle_price' => 157, 'lalamove_car_price' => 220],
            ['district_name' => 'แขวงบางแค', 'grab_motorcycle_price' => 322, 'grab_car_price' => 447, 'lalamove_motorcycle_price' => 218, 'lalamove_car_price' => 292],
            ['district_name' => 'แขวงบางแคเหนือ', 'grab_motorcycle_price' => 273, 'grab_car_price' => 464, 'lalamove_motorcycle_price' => 247, 'lalamove_car_price' => 339],
            ['district_name' => 'แขวงบางไผ่', 'grab_motorcycle_price' => 270, 'grab_car_price' => 416, 'lalamove_motorcycle_price' => 262, 'lalamove_car_price' => 317],
            ['district_name' => 'แขวงหลักสอง', 'grab_motorcycle_price' => 302, 'grab_car_price' => 463, 'lalamove_motorcycle_price' => 338, 'lalamove_car_price' => 343],
            ['district_name' => 'แขวงวัดท่าพระ', 'grab_motorcycle_price' => 213, 'grab_car_price' => 410, 'lalamove_motorcycle_price' => 225, 'lalamove_car_price' => 323],
            ['district_name' => 'แขวงวัดอรุณ', 'grab_motorcycle_price' => 196, 'grab_car_price' => 354, 'lalamove_motorcycle_price' => 308, 'lalamove_car_price' => 256],
            ['district_name' => 'แขวงบางขุนนนท์', 'grab_motorcycle_price' => 206, 'grab_car_price' => 368, 'lalamove_motorcycle_price' => 173, 'lalamove_car_price' => 256],
            ['district_name' => 'แขวงบางขุนศรี', 'grab_motorcycle_price' => 207, 'grab_car_price' => 350, 'lalamove_motorcycle_price' => 178, 'lalamove_car_price' => 256],
            ['district_name' => 'แขวงบ้านช่างหล่อ', 'grab_motorcycle_price' => 200, 'grab_car_price' => 371, 'lalamove_motorcycle_price' => 175, 'lalamove_car_price' => 252],
            ['district_name' => 'แขวงศิริราช', 'grab_motorcycle_price' => 192, 'grab_car_price' => 354, 'lalamove_motorcycle_price' => 246, 'lalamove_car_price' => 243],
            ['district_name' => 'แขวงอรุณอมรินทร์', 'grab_motorcycle_price' => 186, 'grab_car_price' => 346, 'lalamove_motorcycle_price' => 157, 'lalamove_car_price' => 237],
            ['district_name' => 'แขวงคลองจั่น', 'grab_motorcycle_price' => 90, 'grab_car_price' => 182, 'lalamove_motorcycle_price' => 85, 'lalamove_car_price' => 133],
            ['district_name' => 'แขวงหัวหมาก', 'grab_motorcycle_price' => 81, 'grab_car_price' => 168, 'lalamove_motorcycle_price' => 75, 'lalamove_car_price' => 151],
            ['district_name' => 'แขวงท่าข้าม', 'grab_motorcycle_price' => 367, 'grab_car_price' => 554, 'lalamove_motorcycle_price' => 451, 'lalamove_car_price' => 368],
            ['district_name' => 'แขวงแสมดำ', 'grab_motorcycle_price' => 423, 'grab_car_price' => 600, 'lalamove_motorcycle_price' => 385, 'lalamove_car_price' => 357],
            ['district_name' => 'แขวงบางโคล่', 'grab_motorcycle_price' => 194, 'grab_car_price' => 381, 'lalamove_motorcycle_price' => 189, 'lalamove_car_price' => 217],
            ['district_name' => 'แขวงบางคอแหลม', 'grab_motorcycle_price' => 187, 'grab_car_price' => 371, 'lalamove_motorcycle_price' => 189, 'lalamove_car_price' => 238],
            ['district_name' => 'แขวงวัดพระยาไกร', 'grab_motorcycle_price' => 180, 'grab_car_price' => 361, 'lalamove_motorcycle_price' => 161, 'lalamove_car_price' => 209],
            ['district_name' => 'แขวงบางซื่อ', 'grab_motorcycle_price' => 183, 'grab_car_price' => 333, 'lalamove_motorcycle_price' => 137, 'lalamove_car_price' => 209],
            ['district_name' => 'แขวงบางนา', 'grab_motorcycle_price' => 134, 'grab_car_price' => 286, 'lalamove_motorcycle_price' => 152, 'lalamove_car_price' => 216],
            ['district_name' => 'แขวงบางบอน', 'grab_motorcycle_price' => 342, 'grab_car_price' => 582, 'lalamove_motorcycle_price' => 283, 'lalamove_car_price' => 330],
            ['district_name' => 'แขวงบางบำหรุ', 'grab_motorcycle_price' => 191, 'grab_car_price' => 338, 'lalamove_motorcycle_price' => 155, 'lalamove_car_price' => 233],
            ['district_name' => 'แขวงบางพลัด', 'grab_motorcycle_price' => 191, 'grab_car_price' => 348, 'lalamove_motorcycle_price' => 184, 'lalamove_car_price' => 227],
            ['district_name' => 'แขวงบางยี่ขัน', 'grab_motorcycle_price' => 191, 'grab_car_price' => 347, 'lalamove_motorcycle_price' => 164, 'lalamove_car_price' => 238],
            ['district_name' => 'แขวงบางอ้อ', 'grab_motorcycle_price' => 201, 'grab_car_price' => 347, 'lalamove_motorcycle_price' => 157, 'lalamove_car_price' => 237],
            ['district_name' => 'แขวงบางรัก', 'grab_motorcycle_price' => 155, 'grab_car_price' => 326, 'lalamove_motorcycle_price' => 191, 'lalamove_car_price' => 256],
            ['district_name' => 'แขวงมหาพฤฒาราม', 'grab_motorcycle_price' => 162, 'grab_car_price' => 321, 'lalamove_motorcycle_price' => 153, 'lalamove_car_price' => 245],
            ['district_name' => 'แขวงสี่พระยา', 'grab_motorcycle_price' => 153, 'grab_car_price' => 333, 'lalamove_motorcycle_price' => 185, 'lalamove_car_price' => 242],
            ['district_name' => 'แขวงสีลม', 'grab_motorcycle_price' => 144, 'grab_car_price' => 309, 'lalamove_motorcycle_price' => 141, 'lalamove_car_price' => 240],
            ['district_name' => 'แขวงสุริยวงศ์', 'grab_motorcycle_price' => 155, 'grab_car_price' => 341, 'lalamove_motorcycle_price' => 141, 'lalamove_car_price' => 239],
            ['district_name' => 'แขวงคลองกุ่ม', 'grab_motorcycle_price' => 105, 'grab_car_price' => 203, 'lalamove_motorcycle_price' => 118, 'lalamove_car_price' => 197],
            ['district_name' => 'แขวงปทุมวัน', 'grab_motorcycle_price' => 129, 'grab_car_price' => 259, 'lalamove_motorcycle_price' => 151, 'lalamove_car_price' => 228],
            ['district_name' => 'แขวงรองเมือง', 'grab_motorcycle_price' => 152, 'grab_car_price' => 328, 'lalamove_motorcycle_price' => 142, 'lalamove_car_price' => 225],
            ['district_name' => 'แขวงลุมพินี', 'grab_motorcycle_price' => 130, 'grab_car_price' => 260, 'lalamove_motorcycle_price' => 126, 'lalamove_car_price' => 215],
            ['district_name' => 'แขวงวังใหม่', 'grab_motorcycle_price' => 154, 'grab_car_price' => 321, 'lalamove_motorcycle_price' => 162, 'lalamove_car_price' => 228],
            ['district_name' => 'แขวงดอกไม้', 'grab_motorcycle_price' => 140, 'grab_car_price' => 272, 'lalamove_motorcycle_price' => 130, 'lalamove_car_price' => 173],
            ['district_name' => 'แขวงประเวศ', 'grab_motorcycle_price' => 127, 'grab_car_price' => 239, 'lalamove_motorcycle_price' => 104, 'lalamove_car_price' => 169],
            ['district_name' => 'แขวงหนองบอน', 'grab_motorcycle_price' => 121, 'grab_car_price' => 226, 'lalamove_motorcycle_price' => 134, 'lalamove_car_price' => 177],
            ['district_name' => 'แขวงคลองมหานาค', 'grab_motorcycle_price' => 156, 'grab_car_price' => 309, 'lalamove_motorcycle_price' => 180, 'lalamove_car_price' => 192],
            ['district_name' => 'แขวงบ้านบาตร', 'grab_motorcycle_price' => 161, 'grab_car_price' => 321, 'lalamove_motorcycle_price' => 173, 'lalamove_car_price' => 211],
            ['district_name' => 'แขวงป้อมปราบ', 'grab_motorcycle_price' => 151, 'grab_car_price' => 302, 'lalamove_motorcycle_price' => 144, 'lalamove_car_price' => 243],
            ['district_name' => 'แขวงวัดเทพศิรินทร์', 'grab_motorcycle_price' => 156, 'grab_car_price' => 331, 'lalamove_motorcycle_price' => 174, 'lalamove_car_price' => 248],
            ['district_name' => 'แขวงวัดโสมนัส', 'grab_motorcycle_price' => 155, 'grab_car_price' => 304, 'lalamove_motorcycle_price' => 182, 'lalamove_car_price' => 194],
            ['district_name' => 'แขวงสามเสนใน', 'grab_motorcycle_price' => 134, 'grab_car_price' => 277, 'lalamove_motorcycle_price' => 134, 'lalamove_car_price' => 233],
            ['district_name' => 'แขวงบางจาก', 'grab_motorcycle_price' => 112, 'grab_car_price' => 213, 'lalamove_motorcycle_price' => 117, 'lalamove_car_price' => 206],
            ['district_name' => 'แขวงชนะสงคราม', 'grab_motorcycle_price' => 167, 'grab_car_price' => 334, 'lalamove_motorcycle_price' => 190, 'lalamove_car_price' => 220],
            ['district_name' => 'แขวงตลาดยอด', 'grab_motorcycle_price' => 169, 'grab_car_price' => 336, 'lalamove_motorcycle_price' => 190, 'lalamove_car_price' => 219],
            ['district_name' => 'แขวงบวรนิเวศ', 'grab_motorcycle_price' => 167, 'grab_car_price' => 321, 'lalamove_motorcycle_price' => 193, 'lalamove_car_price' => 211],
            ['district_name' => 'แขวงบางขุนพรหม', 'grab_motorcycle_price' => 160, 'grab_car_price' => 323, 'lalamove_motorcycle_price' => 167, 'lalamove_car_price' => 210],
            ['district_name' => 'แขวงบ้านพานถม', 'grab_motorcycle_price' => 160, 'grab_car_price' => 315, 'lalamove_motorcycle_price' => 156, 'lalamove_car_price' => 215],
            ['district_name' => 'แขวงพระบรมมหาราชวัง', 'grab_motorcycle_price' => 173, 'grab_car_price' => 337, 'lalamove_motorcycle_price' => 142, 'lalamove_car_price' => 222],
            ['district_name' => 'แขวงวังบูรพาภิรมย์', 'grab_motorcycle_price' => 178, 'grab_car_price' => 339, 'lalamove_motorcycle_price' => 193, 'lalamove_car_price' => 250],
            ['district_name' => 'แขวงวัดราชบพิธ', 'grab_motorcycle_price' => 169, 'grab_car_price' => 332, 'lalamove_motorcycle_price' => 153, 'lalamove_car_price' => 255],
            ['district_name' => 'แขวงวัดสามพระยา', 'grab_motorcycle_price' => 162, 'grab_car_price' => 327, 'lalamove_motorcycle_price' => 185, 'lalamove_car_price' => 214],
            ['district_name' => 'แขวงศาลเจ้าพ่อเสือ', 'grab_motorcycle_price' => 164, 'grab_car_price' => 322, 'lalamove_motorcycle_price' => 155, 'lalamove_car_price' => 220],
            ['district_name' => 'แขวงสำราญราษฎร์', 'grab_motorcycle_price' => 166, 'grab_car_price' => 323, 'lalamove_motorcycle_price' => 179, 'lalamove_car_price' => 217],
            ['district_name' => 'แขวงเสาชิงช้า', 'grab_motorcycle_price' => 164, 'grab_car_price' => 321, 'lalamove_motorcycle_price' => 213, 'lalamove_car_price' => 193],
            ['district_name' => 'แขวงคลองขวาง', 'grab_motorcycle_price' => 615, 'grab_car_price' => 767, 'lalamove_motorcycle_price' => 219, 'lalamove_car_price' => 291],
            ['district_name' => 'แขวงคูหาสวรรค์', 'grab_motorcycle_price' => 227, 'grab_car_price' => 413, 'lalamove_motorcycle_price' => 239, 'lalamove_car_price' => 366],
            ['district_name' => 'แขวงบางด้วน', 'grab_motorcycle_price' => 245, 'grab_car_price' => 458, 'lalamove_motorcycle_price' => 240, 'lalamove_car_price' => 345],
            ['district_name' => 'แขวงบางแวก', 'grab_motorcycle_price' => 237, 'grab_car_price' => 437, 'lalamove_motorcycle_price' => 229, 'lalamove_car_price' => 288],
            ['district_name' => 'แขวงบางหว้า', 'grab_motorcycle_price' => 220, 'grab_car_price' => 432, 'lalamove_motorcycle_price' => 206, 'lalamove_car_price' => 270],
            ['district_name' => 'แขวงปากคลองภาษีเจริญ', 'grab_motorcycle_price' => 254, 'grab_car_price' => 469, 'lalamove_motorcycle_price' => 191, 'lalamove_car_price' => 308],
            ['district_name' => 'แขวงมีนบุรี', 'grab_motorcycle_price' => 164, 'grab_car_price' => 354, 'lalamove_motorcycle_price' => 195, 'lalamove_car_price' => 248],
            ['district_name' => 'แขวงแสนแสบ', 'grab_motorcycle_price' => 185, 'grab_car_price' => 380, 'lalamove_motorcycle_price' => 170, 'lalamove_car_price' => 238],
            ['district_name' => 'แขวงช่องนนทรี', 'grab_motorcycle_price' => 167, 'grab_car_price' => 339, 'lalamove_motorcycle_price' => 153, 'lalamove_car_price' => 237],
            ['district_name' => 'แขวงบางโพงพาง', 'grab_motorcycle_price' => 181, 'grab_car_price' => 355, 'lalamove_motorcycle_price' => 189, 'lalamove_car_price' => 266],
            ['district_name' => 'แขวงถนนเพชรบุรี', 'grab_motorcycle_price' => 142, 'grab_car_price' => 287, 'lalamove_motorcycle_price' => 154, 'lalamove_car_price' => 270],
            ['district_name' => 'แขวงถนนพญาไท', 'grab_motorcycle_price' => 147, 'grab_car_price' => 294, 'lalamove_motorcycle_price' => 140, 'lalamove_car_price' => 254],
            ['district_name' => 'แขวงทุ่งพญาไท', 'grab_motorcycle_price' => 140, 'grab_car_price' => 285, 'lalamove_motorcycle_price' => 186, 'lalamove_car_price' => 266],
            ['district_name' => 'แขวงมักกะสัน', 'grab_motorcycle_price' => 124, 'grab_car_price' => 251, 'lalamove_motorcycle_price' => 126, 'lalamove_car_price' => 230],
            ['district_name' => 'แขวงบางปะกอก', 'grab_motorcycle_price' => 252, 'grab_car_price' => 404, 'lalamove_motorcycle_price' => 225, 'lalamove_car_price' => 262],
            ['district_name' => 'แขวงราษฎร์บูรณะ', 'grab_motorcycle_price' => 237, 'grab_car_price' => 397, 'lalamove_motorcycle_price' => 215, 'lalamove_car_price' => 252],
            ['district_name' => 'แขวงขุมทอง', 'grab_motorcycle_price' => 273, 'grab_car_price' => 443, 'lalamove_motorcycle_price' => 264, 'lalamove_car_price' => 303],
            ['district_name' => 'แขวงคลองสองต้นนุ่น', 'grab_motorcycle_price' => 145, 'grab_car_price' => 279, 'lalamove_motorcycle_price' => 130, 'lalamove_car_price' => 229],
            ['district_name' => 'แขวงคลองสามประเวศ', 'grab_motorcycle_price' => 160, 'grab_car_price' => 304, 'lalamove_motorcycle_price' => 144, 'lalamove_car_price' => 229],
            ['district_name' => 'แขวงทับยาว', 'grab_motorcycle_price' => 251, 'grab_car_price' => 394, 'lalamove_motorcycle_price' => 224, 'lalamove_car_price' => 237],
            ['district_name' => 'แขวงลาดกระบัง', 'grab_motorcycle_price' => 200, 'grab_car_price' => 323, 'lalamove_motorcycle_price' => 206, 'lalamove_car_price' => 230],
            ['district_name' => 'แขวงลำปลาทิว', 'grab_motorcycle_price' => 222, 'grab_car_price' => 418, 'lalamove_motorcycle_price' => 208, 'lalamove_car_price' => 242],
            ['district_name' => 'แขวงจรเข้บัว', 'grab_motorcycle_price' => 148, 'grab_car_price' => 361, 'lalamove_motorcycle_price' => 173, 'lalamove_car_price' => 279],
            ['district_name' => 'แขวงลาดพร้าว', 'grab_motorcycle_price' => 119, 'grab_car_price' => 265, 'lalamove_motorcycle_price' => 158, 'lalamove_car_price' => 243],
            ['district_name' => 'แขวงวังทองหลาง', 'grab_motorcycle_price' => 71, 'grab_car_price' => 152, 'lalamove_motorcycle_price' => 143, 'lalamove_car_price' => 166],
            ['district_name' => 'แขวงคลองเตยเหนือ', 'grab_motorcycle_price' => 121, 'grab_car_price' => 246, 'lalamove_motorcycle_price' => 168, 'lalamove_car_price' => 235],
            ['district_name' => 'แขวงคลองตันเหนือ', 'grab_motorcycle_price' => 119, 'grab_car_price' => 260, 'lalamove_motorcycle_price' => 152, 'lalamove_car_price' => 206],
            ['district_name' => 'แขวงพระโขนงเหนือ', 'grab_motorcycle_price' => 87, 'grab_car_price' => 177, 'lalamove_motorcycle_price' => 142, 'lalamove_car_price' => 204],
            ['district_name' => 'แขวงสวนหลวง', 'grab_motorcycle_price' => 110, 'grab_car_price' => 209, 'lalamove_motorcycle_price' => 136, 'lalamove_car_price' => 169],
            ['district_name' => 'แขวงสะพานสูง', 'grab_motorcycle_price' => 117, 'grab_car_price' => 291, 'lalamove_motorcycle_price' => 141, 'lalamove_car_price' => 218],
            ['district_name' => 'แขวงจักรวรรดิ', 'grab_motorcycle_price' => 165, 'grab_car_price' => 324, 'lalamove_motorcycle_price' => 189, 'lalamove_car_price' => 307],
            ['district_name' => 'แขวงตลาดน้อย', 'grab_motorcycle_price' => 168, 'grab_car_price' => 327, 'lalamove_motorcycle_price' => 186, 'lalamove_car_price' => 302],
            ['district_name' => 'แขวงสัมพันธวงศ์', 'grab_motorcycle_price' => 168, 'grab_car_price' => 330, 'lalamove_motorcycle_price' => 185, 'lalamove_car_price' => 301],
            ['district_name' => 'แขวงทุ่งมหาเมฆ', 'grab_motorcycle_price' => 151, 'grab_car_price' => 310, 'lalamove_motorcycle_price' => 214, 'lalamove_car_price' => 300],
            ['district_name' => 'แขวงทุ่งวัดดอน', 'grab_motorcycle_price' => 163, 'grab_car_price' => 367, 'lalamove_motorcycle_price' => 225, 'lalamove_car_price' => 262],
            ['district_name' => 'แขวงยานนาวา', 'grab_motorcycle_price' => 164, 'grab_car_price' => 369, 'lalamove_motorcycle_price' => 191, 'lalamove_car_price' => 248],
            ['district_name' => 'แขวงคลองถนน', 'grab_motorcycle_price' => 228, 'grab_car_price' => 449, 'lalamove_motorcycle_price' => 227, 'lalamove_car_price' => 251],
            ['district_name' => 'แขวงสายไหม', 'grab_motorcycle_price' => 250, 'grab_car_price' => 442, 'lalamove_motorcycle_price' => 231, 'lalamove_car_price' => 287],
            ['district_name' => 'แขวงออเงิน', 'grab_motorcycle_price' => 218, 'grab_car_price' => 398, 'lalamove_motorcycle_price' => 183, 'lalamove_car_price' => 252],
            ['district_name' => 'แขวงหนองแขม', 'grab_motorcycle_price' => 412, 'grab_car_price' => 642, 'lalamove_motorcycle_price' => 377, 'lalamove_car_price' => 364],
            ['district_name' => 'แขวงหนองค้างพลู', 'grab_motorcycle_price' => 348, 'grab_car_price' => 558, 'lalamove_motorcycle_price' => 307, 'lalamove_car_price' => 348],
            ['district_name' => 'แขวงกระทุ่มราย', 'grab_motorcycle_price' => 275, 'grab_car_price' => 503, 'lalamove_motorcycle_price' => 322, 'lalamove_car_price' => 354],
            ['district_name' => 'แขวงคลองสิบ', 'grab_motorcycle_price' => 278, 'grab_car_price' => 508, 'lalamove_motorcycle_price' => 271, 'lalamove_car_price' => 323],
            ['district_name' => 'แขวงคลองสิบสอง', 'grab_motorcycle_price' => 442, 'grab_car_price' => 622, 'lalamove_motorcycle_price' => 328, 'lalamove_car_price' => 358],
            ['district_name' => 'แขวงโคกแฝด', 'grab_motorcycle_price' => 262, 'grab_car_price' => 487, 'lalamove_motorcycle_price' => 206, 'lalamove_car_price' => 279],
            ['district_name' => 'แขวงคู้ฝั่งเหนือ', 'grab_motorcycle_price' => 274, 'grab_car_price' => 504, 'lalamove_motorcycle_price' => 201, 'lalamove_car_price' => 273],
            ['district_name' => 'แขวงลำต้อยติ่ง', 'grab_motorcycle_price' => 301, 'grab_car_price' => 548, 'lalamove_motorcycle_price' => 300, 'lalamove_car_price' => 339],
            ['district_name' => 'แขวงลำผักชี', 'grab_motorcycle_price' => 252, 'grab_car_price' => 454, 'lalamove_motorcycle_price' => 198, 'lalamove_car_price' => 268],
            ['district_name' => 'แขวงหนองจอก', 'grab_motorcycle_price' => 294, 'grab_car_price' => 541, 'lalamove_motorcycle_price' => 269, 'lalamove_car_price' => 321],
            ['district_name' => 'แขวงตลาดบางเขน', 'grab_motorcycle_price' => 189, 'grab_car_price' => 402, 'lalamove_motorcycle_price' => 202, 'lalamove_car_price' => 307],
            ['district_name' => 'แขวงทุ่งสองห้อง', 'grab_motorcycle_price' => 222, 'grab_car_price' => 431, 'lalamove_motorcycle_price' => 211, 'lalamove_car_price' => 322],
            ['district_name' => 'แขวงบางกะปิ', 'grab_motorcycle_price' => 82, 'grab_car_price' => 170, 'lalamove_motorcycle_price' => 67, 'lalamove_car_price' => 168],
            ['district_name' => 'แขวงสามเสนนอก', 'grab_motorcycle_price' => 106, 'grab_car_price' => 265, 'lalamove_motorcycle_price' => 107, 'lalamove_car_price' => 161],
            ['district_name' => 'แขวงห้วยขวาง', 'grab_motorcycle_price' => 106, 'grab_car_price' => 207, 'lalamove_motorcycle_price' => 102, 'lalamove_car_price' => 155],
        ];

        foreach ($deliveryPrices as $price) {
            DeliveryPrice::create($price);
        }
    }
}